/* ========================================
   Memoria - DDL Script (Oracle)
   ======================================== */

/* 시퀀스 생성 */
CREATE SEQUENCE SEQ_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CALENDAR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CALENDAR_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENT_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INVITATION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

/* MEMBER 테이블 */
CREATE TABLE MEMBER (
    MEMBER_ID       NUMBER(19)      NOT NULL,
    EMAIL           VARCHAR2(255)   NOT NULL,
    PASSWORD        VARCHAR2(255),
    NICKNAME        VARCHAR2(100)   NOT NULL,
    PROFILE_IMAGE   VARCHAR2(500),
    PROVIDER        VARCHAR2(20),
    PROVIDER_ID     VARCHAR2(255),
    ROLE            VARCHAR2(20)    DEFAULT 'USER' NOT NULL,
    DEL_YN          CHAR(1)         DEFAULT 'N' NOT NULL,
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL)
);

COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 ID (PK)';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호 (암호화)';
COMMENT ON COLUMN MEMBER.NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.PROFILE_IMAGE IS '프로필 이미지 URL';
COMMENT ON COLUMN MEMBER.PROVIDER IS 'OAuth 제공자 (KAKAO, GOOGLE)';
COMMENT ON COLUMN MEMBER.PROVIDER_ID IS 'OAuth 제공자 ID';
COMMENT ON COLUMN MEMBER.ROLE IS '역할 (USER, ADMIN)';
COMMENT ON COLUMN MEMBER.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN MEMBER.CRE_ID IS '생성자';
COMMENT ON COLUMN MEMBER.CRE_DT IS '생성일시';
COMMENT ON COLUMN MEMBER.UPD_ID IS '수정자';
COMMENT ON COLUMN MEMBER.UPD_DT IS '수정일시';

/* CALENDAR 테이블 */
CREATE TABLE CALENDAR (
    CALENDAR_ID     NUMBER(19)      NOT NULL,
    NAME            VARCHAR2(200)   NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    COLOR           VARCHAR2(20)    DEFAULT '#4A90D9' NOT NULL,
    INVITE_CODE     VARCHAR2(50),
    OWNER_ID        NUMBER(19)      NOT NULL,
    DEL_YN          CHAR(1)         DEFAULT 'N' NOT NULL,
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_CALENDAR PRIMARY KEY (CALENDAR_ID),
    CONSTRAINT UK_CALENDAR_INVITE_CODE UNIQUE (INVITE_CODE)
);

COMMENT ON TABLE CALENDAR IS '캘린더';
COMMENT ON COLUMN CALENDAR.CALENDAR_ID IS '캘린더 ID (PK)';
COMMENT ON COLUMN CALENDAR.NAME IS '캘린더 이름';
COMMENT ON COLUMN CALENDAR.DESCRIPTION IS '캘린더 설명';
COMMENT ON COLUMN CALENDAR.COLOR IS '캘린더 색상 (HEX)';
COMMENT ON COLUMN CALENDAR.INVITE_CODE IS '초대 코드';
COMMENT ON COLUMN CALENDAR.OWNER_ID IS '소유자 회원 ID';
COMMENT ON COLUMN CALENDAR.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN CALENDAR.CRE_ID IS '생성자';
COMMENT ON COLUMN CALENDAR.CRE_DT IS '생성일시';
COMMENT ON COLUMN CALENDAR.UPD_ID IS '수정자';
COMMENT ON COLUMN CALENDAR.UPD_DT IS '수정일시';

/* CALENDAR_MEMBER 테이블 */
CREATE TABLE CALENDAR_MEMBER (
    CALENDAR_MEMBER_ID  NUMBER(19)      NOT NULL,
    CALENDAR_ID         NUMBER(19)      NOT NULL,
    MEMBER_ID           NUMBER(19)      NOT NULL,
    ROLE                VARCHAR2(20)    DEFAULT 'MEMBER' NOT NULL,
    COLOR               VARCHAR2(20),
    DEL_YN              CHAR(1)         DEFAULT 'N' NOT NULL,
    CRE_ID              VARCHAR2(100),
    CRE_DT              TIMESTAMP,
    UPD_ID              VARCHAR2(100),
    UPD_DT              TIMESTAMP,
    CONSTRAINT PK_CALENDAR_MEMBER PRIMARY KEY (CALENDAR_MEMBER_ID)
);

CREATE INDEX IDX_CALENDAR_MEMBER_CAL ON CALENDAR_MEMBER (CALENDAR_ID);
CREATE INDEX IDX_CALENDAR_MEMBER_MEM ON CALENDAR_MEMBER (MEMBER_ID);

COMMENT ON TABLE CALENDAR_MEMBER IS '캘린더 참여 회원';
COMMENT ON COLUMN CALENDAR_MEMBER.CALENDAR_MEMBER_ID IS '캘린더 참여 ID (PK)';
COMMENT ON COLUMN CALENDAR_MEMBER.CALENDAR_ID IS '캘린더 ID';
COMMENT ON COLUMN CALENDAR_MEMBER.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN CALENDAR_MEMBER.ROLE IS '캘린더 내 역할 (OWNER, ADMIN, MEMBER)';
COMMENT ON COLUMN CALENDAR_MEMBER.COLOR IS '개인 색상 설정';
COMMENT ON COLUMN CALENDAR_MEMBER.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN CALENDAR_MEMBER.CRE_ID IS '생성자';
COMMENT ON COLUMN CALENDAR_MEMBER.CRE_DT IS '생성일시';
COMMENT ON COLUMN CALENDAR_MEMBER.UPD_ID IS '수정자';
COMMENT ON COLUMN CALENDAR_MEMBER.UPD_DT IS '수정일시';

/* EVENT 테이블 */
CREATE TABLE EVENT (
    EVENT_ID        NUMBER(19)      NOT NULL,
    CALENDAR_ID     NUMBER(19)      NOT NULL,
    TITLE           VARCHAR2(300)   NOT NULL,
    DESCRIPTION     VARCHAR2(2000),
    LOCATION        VARCHAR2(500),
    START_DT        TIMESTAMP       NOT NULL,
    END_DT          TIMESTAMP       NOT NULL,
    ALL_DAY_YN      CHAR(1)         DEFAULT 'N' NOT NULL,
    COLOR           VARCHAR2(20),
    REPEAT_TYPE     VARCHAR2(20),
    REMIND_MINUTES  NUMBER(10),
    CREATOR_ID      NUMBER(19)      NOT NULL,
    DEL_YN          CHAR(1)         DEFAULT 'N' NOT NULL,
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_EVENT PRIMARY KEY (EVENT_ID)
);

CREATE INDEX IDX_EVENT_CALENDAR ON EVENT (CALENDAR_ID);
CREATE INDEX IDX_EVENT_CREATOR ON EVENT (CREATOR_ID);
CREATE INDEX IDX_EVENT_START_DT ON EVENT (START_DT);

COMMENT ON TABLE EVENT IS '일정(이벤트)';
COMMENT ON COLUMN EVENT.EVENT_ID IS '이벤트 ID (PK)';
COMMENT ON COLUMN EVENT.CALENDAR_ID IS '캘린더 ID';
COMMENT ON COLUMN EVENT.TITLE IS '일정 제목';
COMMENT ON COLUMN EVENT.DESCRIPTION IS '일정 설명';
COMMENT ON COLUMN EVENT.LOCATION IS '장소';
COMMENT ON COLUMN EVENT.START_DT IS '시작 일시';
COMMENT ON COLUMN EVENT.END_DT IS '종료 일시';
COMMENT ON COLUMN EVENT.ALL_DAY_YN IS '종일 여부 (Y/N)';
COMMENT ON COLUMN EVENT.COLOR IS '일정 색상';
COMMENT ON COLUMN EVENT.REPEAT_TYPE IS '반복 유형 (NONE, DAILY, WEEKLY, MONTHLY, YEARLY)';
COMMENT ON COLUMN EVENT.REMIND_MINUTES IS '알림 (분 단위, 이벤트 전)';
COMMENT ON COLUMN EVENT.CREATOR_ID IS '생성자 회원 ID';
COMMENT ON COLUMN EVENT.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN EVENT.CRE_ID IS '생성자';
COMMENT ON COLUMN EVENT.CRE_DT IS '생성일시';
COMMENT ON COLUMN EVENT.UPD_ID IS '수정자';
COMMENT ON COLUMN EVENT.UPD_DT IS '수정일시';

/* EVENT_COMMENT 테이블 */
CREATE TABLE EVENT_COMMENT (
    EVENT_COMMENT_ID    NUMBER(19)      NOT NULL,
    EVENT_ID            NUMBER(19)      NOT NULL,
    MEMBER_ID           NUMBER(19)      NOT NULL,
    CONTENT             VARCHAR2(1000)  NOT NULL,
    DEL_YN              CHAR(1)         DEFAULT 'N' NOT NULL,
    CRE_ID              VARCHAR2(100),
    CRE_DT              TIMESTAMP,
    UPD_ID              VARCHAR2(100),
    UPD_DT              TIMESTAMP,
    CONSTRAINT PK_EVENT_COMMENT PRIMARY KEY (EVENT_COMMENT_ID)
);

CREATE INDEX IDX_EVENT_COMMENT_EVENT ON EVENT_COMMENT (EVENT_ID);
CREATE INDEX IDX_EVENT_COMMENT_MEMBER ON EVENT_COMMENT (MEMBER_ID);

COMMENT ON TABLE EVENT_COMMENT IS '이벤트 댓글';
COMMENT ON COLUMN EVENT_COMMENT.EVENT_COMMENT_ID IS '이벤트 댓글 ID (PK)';
COMMENT ON COLUMN EVENT_COMMENT.EVENT_ID IS '이벤트 ID';
COMMENT ON COLUMN EVENT_COMMENT.MEMBER_ID IS '작성자 회원 ID';
COMMENT ON COLUMN EVENT_COMMENT.CONTENT IS '댓글 내용';
COMMENT ON COLUMN EVENT_COMMENT.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN EVENT_COMMENT.CRE_ID IS '생성자';
COMMENT ON COLUMN EVENT_COMMENT.CRE_DT IS '생성일시';
COMMENT ON COLUMN EVENT_COMMENT.UPD_ID IS '수정자';
COMMENT ON COLUMN EVENT_COMMENT.UPD_DT IS '수정일시';

/* INVITATION 테이블 */
CREATE TABLE INVITATION (
    INVITATION_ID   NUMBER(19)      NOT NULL,
    CALENDAR_ID     NUMBER(19)      NOT NULL,
    INVITER_ID      NUMBER(19)      NOT NULL,
    INVITEE_EMAIL   VARCHAR2(255),
    INVITE_TYPE     VARCHAR2(20),
    STATUS          VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    TOKEN           VARCHAR2(100)   NOT NULL,
    EXPIRED_AT      TIMESTAMP,
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_INVITATION PRIMARY KEY (INVITATION_ID),
    CONSTRAINT UK_INVITATION_TOKEN UNIQUE (TOKEN)
);

CREATE INDEX IDX_INVITATION_CALENDAR ON INVITATION (CALENDAR_ID);
CREATE INDEX IDX_INVITATION_INVITEE ON INVITATION (INVITEE_EMAIL);

COMMENT ON TABLE INVITATION IS '캘린더 초대';
COMMENT ON COLUMN INVITATION.INVITATION_ID IS '초대 ID (PK)';
COMMENT ON COLUMN INVITATION.CALENDAR_ID IS '캘린더 ID';
COMMENT ON COLUMN INVITATION.INVITER_ID IS '초대한 회원 ID';
COMMENT ON COLUMN INVITATION.INVITEE_EMAIL IS '초대받은 이메일';
COMMENT ON COLUMN INVITATION.INVITE_TYPE IS '초대 유형 (KAKAO, EMAIL)';
COMMENT ON COLUMN INVITATION.STATUS IS '초대 상태 (PENDING, ACCEPTED, REJECTED, EXPIRED)';
COMMENT ON COLUMN INVITATION.TOKEN IS '초대 토큰';
COMMENT ON COLUMN INVITATION.EXPIRED_AT IS '만료 일시';
COMMENT ON COLUMN INVITATION.CRE_ID IS '생성자';
COMMENT ON COLUMN INVITATION.CRE_DT IS '생성일시';
COMMENT ON COLUMN INVITATION.UPD_ID IS '수정자';
COMMENT ON COLUMN INVITATION.UPD_DT IS '수정일시';
