/* ========================================
   Memoria - DDL Script (Oracle)
   ======================================== */

/* 시퀀스 생성 */
CREATE SEQUENCE SEQ_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DIARY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DIARY_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENT_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INVITATION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TICKET_BALANCE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TICKET_TRANSACTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SHOP_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USER_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

/* MEMBER 테이블 */
CREATE TABLE MEMBER (
    MEMBER_ID       NUMBER(19)      NOT NULL,
    EMAIL           VARCHAR2(255)   NOT NULL,
    PASSWORD        VARCHAR2(255),
    NICKNAME        VARCHAR2(100)   NOT NULL,
    PROFILE_IMAGE   VARCHAR2(500),
    PROVIDER        VARCHAR2(20),
    PROVIDER_ID     VARCHAR2(255),
    ROLE            VARCHAR2(20)    DEFAULT 'USER' NOT NULL,
    DEL_YN          CHAR(1)         DEFAULT 'N' NOT NULL,
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL)
);

COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 ID (PK)';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호 (암호화)';
COMMENT ON COLUMN MEMBER.NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.PROFILE_IMAGE IS '프로필 이미지 URL';
COMMENT ON COLUMN MEMBER.PROVIDER IS 'OAuth 제공자 (KAKAO, GOOGLE)';
COMMENT ON COLUMN MEMBER.PROVIDER_ID IS 'OAuth 제공자 ID';
COMMENT ON COLUMN MEMBER.ROLE IS '역할 (USER, ADMIN)';
COMMENT ON COLUMN MEMBER.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN MEMBER.CRE_ID IS '생성자';
COMMENT ON COLUMN MEMBER.CRE_DT IS '생성일시';
COMMENT ON COLUMN MEMBER.UPD_ID IS '수정자';
COMMENT ON COLUMN MEMBER.UPD_DT IS '수정일시';

/* DIARY 테이블 */
CREATE TABLE DIARY (
    DIARY_ID        NUMBER(19)      NOT NULL,
    NAME            VARCHAR2(200)   NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    COLOR           VARCHAR2(20)    DEFAULT '#4A90D9' NOT NULL,
    INVITE_CODE     VARCHAR2(50),
    OWNER_ID        NUMBER(19)      NOT NULL,
    LOGO_ID         NUMBER(19),
    THEME_ID        NUMBER(19),
    DIARY_TYPE      VARCHAR2(20)    DEFAULT 'GENERAL' NOT NULL,
    DEL_YN          CHAR(1)         DEFAULT 'N' NOT NULL,
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_DIARY PRIMARY KEY (DIARY_ID),
    CONSTRAINT UK_DIARY_INVITE_CODE UNIQUE (INVITE_CODE)
);

COMMENT ON TABLE DIARY IS '다이어리';
COMMENT ON COLUMN DIARY.DIARY_ID IS '다이어리 ID (PK)';
COMMENT ON COLUMN DIARY.NAME IS '다이어리 이름';
COMMENT ON COLUMN DIARY.DESCRIPTION IS '다이어리 설명';
COMMENT ON COLUMN DIARY.COLOR IS '다이어리 색상 (HEX)';
COMMENT ON COLUMN DIARY.INVITE_CODE IS '초대 코드';
COMMENT ON COLUMN DIARY.OWNER_ID IS '소유자 회원 ID';
COMMENT ON COLUMN DIARY.LOGO_ID IS '적용된 로고 아이템 ID';
COMMENT ON COLUMN DIARY.THEME_ID IS '적용된 테마 아이템 ID';
COMMENT ON COLUMN DIARY.DIARY_TYPE IS '다이어리 유형 (GENERAL, COUPLE, FAMILY, TEAM, WEDDING)';
COMMENT ON COLUMN DIARY.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN DIARY.CRE_ID IS '생성자';
COMMENT ON COLUMN DIARY.CRE_DT IS '생성일시';
COMMENT ON COLUMN DIARY.UPD_ID IS '수정자';
COMMENT ON COLUMN DIARY.UPD_DT IS '수정일시';

/* DIARY_MEMBER 테이블 */
CREATE TABLE DIARY_MEMBER (
    DIARY_MEMBER_ID     NUMBER(19)      NOT NULL,
    DIARY_ID            NUMBER(19)      NOT NULL,
    MEMBER_ID           NUMBER(19)      NOT NULL,
    ROLE                VARCHAR2(20)    DEFAULT 'MEMBER' NOT NULL,
    COLOR               VARCHAR2(20),
    DEL_YN              CHAR(1)         DEFAULT 'N' NOT NULL,
    CRE_ID              VARCHAR2(100),
    CRE_DT              TIMESTAMP,
    UPD_ID              VARCHAR2(100),
    UPD_DT              TIMESTAMP,
    CONSTRAINT PK_DIARY_MEMBER PRIMARY KEY (DIARY_MEMBER_ID)
);

CREATE INDEX IDX_DIARY_MEMBER_DIARY ON DIARY_MEMBER (DIARY_ID);
CREATE INDEX IDX_DIARY_MEMBER_MEM ON DIARY_MEMBER (MEMBER_ID);

COMMENT ON TABLE DIARY_MEMBER IS '다이어리 참여 회원';
COMMENT ON COLUMN DIARY_MEMBER.DIARY_MEMBER_ID IS '다이어리 참여 ID (PK)';
COMMENT ON COLUMN DIARY_MEMBER.DIARY_ID IS '다이어리 ID';
COMMENT ON COLUMN DIARY_MEMBER.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN DIARY_MEMBER.ROLE IS '다이어리 내 역할 (OWNER, ADMIN, MEMBER)';
COMMENT ON COLUMN DIARY_MEMBER.COLOR IS '개인 색상 설정';
COMMENT ON COLUMN DIARY_MEMBER.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN DIARY_MEMBER.CRE_ID IS '생성자';
COMMENT ON COLUMN DIARY_MEMBER.CRE_DT IS '생성일시';
COMMENT ON COLUMN DIARY_MEMBER.UPD_ID IS '수정자';
COMMENT ON COLUMN DIARY_MEMBER.UPD_DT IS '수정일시';

/* EVENT 테이블 */
CREATE TABLE EVENT (
    EVENT_ID        NUMBER(19)      NOT NULL,
    DIARY_ID        NUMBER(19)      NOT NULL,
    TITLE           VARCHAR2(300)   NOT NULL,
    DESCRIPTION     VARCHAR2(2000),
    LOCATION        VARCHAR2(500),
    START_DT        TIMESTAMP       NOT NULL,
    END_DT          TIMESTAMP       NOT NULL,
    ALL_DAY_YN      CHAR(1)         DEFAULT 'N' NOT NULL,
    COLOR           VARCHAR2(20),
    REPEAT_TYPE     VARCHAR2(20),
    REMIND_MINUTES  NUMBER(10),
    CREATOR_ID      NUMBER(19)      NOT NULL,
    DEL_YN          CHAR(1)         DEFAULT 'N' NOT NULL,
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_EVENT PRIMARY KEY (EVENT_ID)
);

CREATE INDEX IDX_EVENT_DIARY ON EVENT (DIARY_ID);
CREATE INDEX IDX_EVENT_CREATOR ON EVENT (CREATOR_ID);
CREATE INDEX IDX_EVENT_START_DT ON EVENT (START_DT);

COMMENT ON TABLE EVENT IS '일정(이벤트)';
COMMENT ON COLUMN EVENT.EVENT_ID IS '이벤트 ID (PK)';
COMMENT ON COLUMN EVENT.DIARY_ID IS '다이어리 ID';
COMMENT ON COLUMN EVENT.TITLE IS '일정 제목';
COMMENT ON COLUMN EVENT.DESCRIPTION IS '일정 설명';
COMMENT ON COLUMN EVENT.LOCATION IS '장소';
COMMENT ON COLUMN EVENT.START_DT IS '시작 일시';
COMMENT ON COLUMN EVENT.END_DT IS '종료 일시';
COMMENT ON COLUMN EVENT.ALL_DAY_YN IS '종일 여부 (Y/N)';
COMMENT ON COLUMN EVENT.COLOR IS '일정 색상';
COMMENT ON COLUMN EVENT.REPEAT_TYPE IS '반복 유형 (NONE, DAILY, WEEKLY, MONTHLY, YEARLY)';
COMMENT ON COLUMN EVENT.REMIND_MINUTES IS '알림 (분 단위, 이벤트 전)';
COMMENT ON COLUMN EVENT.CREATOR_ID IS '생성자 회원 ID';
COMMENT ON COLUMN EVENT.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN EVENT.CRE_ID IS '생성자';
COMMENT ON COLUMN EVENT.CRE_DT IS '생성일시';
COMMENT ON COLUMN EVENT.UPD_ID IS '수정자';
COMMENT ON COLUMN EVENT.UPD_DT IS '수정일시';

/* EVENT_COMMENT 테이블 */
CREATE TABLE EVENT_COMMENT (
    EVENT_COMMENT_ID    NUMBER(19)      NOT NULL,
    EVENT_ID            NUMBER(19)      NOT NULL,
    MEMBER_ID           NUMBER(19)      NOT NULL,
    CONTENT             VARCHAR2(1000)  NOT NULL,
    DEL_YN              CHAR(1)         DEFAULT 'N' NOT NULL,
    CRE_ID              VARCHAR2(100),
    CRE_DT              TIMESTAMP,
    UPD_ID              VARCHAR2(100),
    UPD_DT              TIMESTAMP,
    CONSTRAINT PK_EVENT_COMMENT PRIMARY KEY (EVENT_COMMENT_ID)
);

CREATE INDEX IDX_EVENT_COMMENT_EVENT ON EVENT_COMMENT (EVENT_ID);
CREATE INDEX IDX_EVENT_COMMENT_MEMBER ON EVENT_COMMENT (MEMBER_ID);

COMMENT ON TABLE EVENT_COMMENT IS '이벤트 댓글';
COMMENT ON COLUMN EVENT_COMMENT.EVENT_COMMENT_ID IS '이벤트 댓글 ID (PK)';
COMMENT ON COLUMN EVENT_COMMENT.EVENT_ID IS '이벤트 ID';
COMMENT ON COLUMN EVENT_COMMENT.MEMBER_ID IS '작성자 회원 ID';
COMMENT ON COLUMN EVENT_COMMENT.CONTENT IS '댓글 내용';
COMMENT ON COLUMN EVENT_COMMENT.DEL_YN IS '삭제 여부 (Y/N)';
COMMENT ON COLUMN EVENT_COMMENT.CRE_ID IS '생성자';
COMMENT ON COLUMN EVENT_COMMENT.CRE_DT IS '생성일시';
COMMENT ON COLUMN EVENT_COMMENT.UPD_ID IS '수정자';
COMMENT ON COLUMN EVENT_COMMENT.UPD_DT IS '수정일시';

/* INVITATION 테이블 */
CREATE TABLE INVITATION (
    INVITATION_ID   NUMBER(19)      NOT NULL,
    DIARY_ID        NUMBER(19)      NOT NULL,
    INVITER_ID      NUMBER(19)      NOT NULL,
    INVITEE_EMAIL   VARCHAR2(255),
    INVITE_TYPE     VARCHAR2(20),
    STATUS          VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    TOKEN           VARCHAR2(100)   NOT NULL,
    EXPIRED_AT      TIMESTAMP,
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_INVITATION PRIMARY KEY (INVITATION_ID),
    CONSTRAINT UK_INVITATION_TOKEN UNIQUE (TOKEN)
);

CREATE INDEX IDX_INVITATION_DIARY ON INVITATION (DIARY_ID);
CREATE INDEX IDX_INVITATION_INVITEE ON INVITATION (INVITEE_EMAIL);

COMMENT ON TABLE INVITATION IS '다이어리 초대';
COMMENT ON COLUMN INVITATION.INVITATION_ID IS '초대 ID (PK)';
COMMENT ON COLUMN INVITATION.DIARY_ID IS '다이어리 ID';
COMMENT ON COLUMN INVITATION.INVITER_ID IS '초대한 회원 ID';
COMMENT ON COLUMN INVITATION.INVITEE_EMAIL IS '초대받은 이메일';
COMMENT ON COLUMN INVITATION.INVITE_TYPE IS '초대 유형 (KAKAO, EMAIL)';
COMMENT ON COLUMN INVITATION.STATUS IS '초대 상태 (PENDING, ACCEPTED, REJECTED, EXPIRED)';
COMMENT ON COLUMN INVITATION.TOKEN IS '초대 토큰';
COMMENT ON COLUMN INVITATION.EXPIRED_AT IS '만료 일시';
COMMENT ON COLUMN INVITATION.CRE_ID IS '생성자';
COMMENT ON COLUMN INVITATION.CRE_DT IS '생성일시';
COMMENT ON COLUMN INVITATION.UPD_ID IS '수정자';
COMMENT ON COLUMN INVITATION.UPD_DT IS '수정일시';

/* TICKET_BALANCE 테이블 */
CREATE TABLE TICKET_BALANCE (
    BALANCE_ID      NUMBER(19)      NOT NULL,
    MEMBER_ID       NUMBER(19)      NOT NULL,
    BALANCE         NUMBER(10)      DEFAULT 0 NOT NULL,
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_TICKET_BALANCE PRIMARY KEY (BALANCE_ID)
);

CREATE INDEX IDX_TICKET_BALANCE_MEMBER ON TICKET_BALANCE (MEMBER_ID);

COMMENT ON TABLE TICKET_BALANCE IS '티켓 잔액';
COMMENT ON COLUMN TICKET_BALANCE.BALANCE_ID IS '잔액 ID (PK)';
COMMENT ON COLUMN TICKET_BALANCE.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN TICKET_BALANCE.BALANCE IS '현재 티켓 잔액';
COMMENT ON COLUMN TICKET_BALANCE.CRE_ID IS '생성자';
COMMENT ON COLUMN TICKET_BALANCE.CRE_DT IS '생성일시';
COMMENT ON COLUMN TICKET_BALANCE.UPD_ID IS '수정자';
COMMENT ON COLUMN TICKET_BALANCE.UPD_DT IS '수정일시';

/* TICKET_TRANSACTION 테이블 */
CREATE TABLE TICKET_TRANSACTION (
    TRANSACTION_ID  NUMBER(19)      NOT NULL,
    MEMBER_ID       NUMBER(19)      NOT NULL,
    TYPE            VARCHAR2(20)    NOT NULL,
    AMOUNT          NUMBER(10)      NOT NULL,
    BALANCE_AFTER   NUMBER(10)      NOT NULL,
    ITEM_TYPE       VARCHAR2(50),
    ITEM_ID         NUMBER(19),
    DESCRIPTION     VARCHAR2(500),
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_TICKET_TRANSACTION PRIMARY KEY (TRANSACTION_ID)
);

CREATE INDEX IDX_TICKET_TXN_MEMBER ON TICKET_TRANSACTION (MEMBER_ID);

COMMENT ON TABLE TICKET_TRANSACTION IS '티켓 거래 내역';
COMMENT ON COLUMN TICKET_TRANSACTION.TRANSACTION_ID IS '거래 ID (PK)';
COMMENT ON COLUMN TICKET_TRANSACTION.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN TICKET_TRANSACTION.TYPE IS '거래 유형 (CHARGE, USE, REFUND)';
COMMENT ON COLUMN TICKET_TRANSACTION.AMOUNT IS '변동 수량 (양수)';
COMMENT ON COLUMN TICKET_TRANSACTION.BALANCE_AFTER IS '변동 후 잔액';
COMMENT ON COLUMN TICKET_TRANSACTION.ITEM_TYPE IS '아이템 유형 (DIARY, LOGO, THEME, WEDDING 등)';
COMMENT ON COLUMN TICKET_TRANSACTION.ITEM_ID IS '구매한 아이템 ID';
COMMENT ON COLUMN TICKET_TRANSACTION.DESCRIPTION IS '설명';
COMMENT ON COLUMN TICKET_TRANSACTION.CRE_ID IS '생성자';
COMMENT ON COLUMN TICKET_TRANSACTION.CRE_DT IS '생성일시';
COMMENT ON COLUMN TICKET_TRANSACTION.UPD_ID IS '수정자';
COMMENT ON COLUMN TICKET_TRANSACTION.UPD_DT IS '수정일시';

/* SHOP_ITEM 테이블 */
CREATE TABLE SHOP_ITEM (
    ITEM_ID         NUMBER(19)      NOT NULL,
    CATEGORY        VARCHAR2(30)    NOT NULL,
    NAME            VARCHAR2(200)   NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    PRICE           NUMBER(10)      DEFAULT 0 NOT NULL,
    IMAGE_URL       VARCHAR2(500),
    METADATA        VARCHAR2(2000),
    ACTIVE_YN       CHAR(1)         DEFAULT 'Y' NOT NULL,
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_SHOP_ITEM PRIMARY KEY (ITEM_ID)
);

CREATE INDEX IDX_SHOP_ITEM_CATEGORY ON SHOP_ITEM (CATEGORY);

COMMENT ON TABLE SHOP_ITEM IS '상점 아이템';
COMMENT ON COLUMN SHOP_ITEM.ITEM_ID IS '아이템 ID (PK)';
COMMENT ON COLUMN SHOP_ITEM.CATEGORY IS '카테고리 (LOGO, THEME, DIARY_SLOT, WEDDING_FEATURE)';
COMMENT ON COLUMN SHOP_ITEM.NAME IS '아이템 이름';
COMMENT ON COLUMN SHOP_ITEM.DESCRIPTION IS '아이템 설명';
COMMENT ON COLUMN SHOP_ITEM.PRICE IS '티켓 가격 (0이면 무료)';
COMMENT ON COLUMN SHOP_ITEM.IMAGE_URL IS '미리보기 이미지 URL';
COMMENT ON COLUMN SHOP_ITEM.METADATA IS 'JSON 메타데이터 (테마 설정값, 로고 경로 등)';
COMMENT ON COLUMN SHOP_ITEM.ACTIVE_YN IS '판매 여부 (Y/N)';
COMMENT ON COLUMN SHOP_ITEM.CRE_ID IS '생성자';
COMMENT ON COLUMN SHOP_ITEM.CRE_DT IS '생성일시';
COMMENT ON COLUMN SHOP_ITEM.UPD_ID IS '수정자';
COMMENT ON COLUMN SHOP_ITEM.UPD_DT IS '수정일시';

/* USER_ITEM 테이블 */
CREATE TABLE USER_ITEM (
    USER_ITEM_ID    NUMBER(19)      NOT NULL,
    MEMBER_ID       NUMBER(19)      NOT NULL,
    ITEM_ID         NUMBER(19)      NOT NULL,
    PURCHASED_AT    TIMESTAMP       NOT NULL,
    CRE_ID          VARCHAR2(100),
    CRE_DT          TIMESTAMP,
    UPD_ID          VARCHAR2(100),
    UPD_DT          TIMESTAMP,
    CONSTRAINT PK_USER_ITEM PRIMARY KEY (USER_ITEM_ID)
);

CREATE INDEX IDX_USER_ITEM_MEMBER ON USER_ITEM (MEMBER_ID);
CREATE INDEX IDX_USER_ITEM_ITEM ON USER_ITEM (ITEM_ID);

COMMENT ON TABLE USER_ITEM IS '사용자 보유 아이템';
COMMENT ON COLUMN USER_ITEM.USER_ITEM_ID IS '사용자 아이템 ID (PK)';
COMMENT ON COLUMN USER_ITEM.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN USER_ITEM.ITEM_ID IS '상점 아이템 ID';
COMMENT ON COLUMN USER_ITEM.PURCHASED_AT IS '구매 일시';
COMMENT ON COLUMN USER_ITEM.CRE_ID IS '생성자';
COMMENT ON COLUMN USER_ITEM.CRE_DT IS '생성일시';
COMMENT ON COLUMN USER_ITEM.UPD_ID IS '수정자';
COMMENT ON COLUMN USER_ITEM.UPD_DT IS '수정일시';
