/* ========================================
   Memoria - Drop Script (Oracle)
   순서: 인덱스 → 테이블 → 시퀀스
   ======================================== */

/* 인덱스 삭제 */
DROP INDEX IDX_INVITATION_INVITEE;
DROP INDEX IDX_INVITATION_CALENDAR;
DROP INDEX IDX_EVENT_COMMENT_MEMBER;
DROP INDEX IDX_EVENT_COMMENT_EVENT;
DROP INDEX IDX_EVENT_START_DT;
DROP INDEX IDX_EVENT_CREATOR;
DROP INDEX IDX_EVENT_CALENDAR;
DROP INDEX IDX_CALENDAR_MEMBER_MEM;
DROP INDEX IDX_CALENDAR_MEMBER_CAL;

/* 테이블 삭제 */
DROP TABLE INVITATION;
DROP TABLE EVENT_COMMENT;
DROP TABLE EVENT;
DROP TABLE CALENDAR_MEMBER;
DROP TABLE CALENDAR;
DROP TABLE MEMBER;

/* 시퀀스 삭제 */
DROP SEQUENCE SEQ_INVITATION;
DROP SEQUENCE SEQ_EVENT_COMMENT;
DROP SEQUENCE SEQ_EVENT;
DROP SEQUENCE SEQ_CALENDAR_MEMBER;
DROP SEQUENCE SEQ_CALENDAR;
DROP SEQUENCE SEQ_MEMBER;
