/* ========================================
   Memoria - Drop Script (Oracle)
   순서: 인덱스 → 테이블 → 시퀀스
   ======================================== */

/* 인덱스 삭제 */
DROP INDEX IDX_USER_ITEM_ITEM;
DROP INDEX IDX_USER_ITEM_MEMBER;
DROP INDEX IDX_SHOP_ITEM_CATEGORY;
DROP INDEX IDX_TICKET_TXN_MEMBER;
DROP INDEX IDX_TICKET_BALANCE_MEMBER;
DROP INDEX IDX_INVITATION_INVITEE;
DROP INDEX IDX_INVITATION_DIARY;
DROP INDEX IDX_EVENT_COMMENT_MEMBER;
DROP INDEX IDX_EVENT_COMMENT_EVENT;
DROP INDEX IDX_EVENT_START_DT;
DROP INDEX IDX_EVENT_CREATOR;
DROP INDEX IDX_EVENT_DIARY;
DROP INDEX IDX_DIARY_MEMBER_MEM;
DROP INDEX IDX_DIARY_MEMBER_DIARY;

/* 테이블 삭제 */
DROP TABLE USER_ITEM;
DROP TABLE SHOP_ITEM;
DROP TABLE TICKET_TRANSACTION;
DROP TABLE TICKET_BALANCE;
DROP TABLE INVITATION;
DROP TABLE EVENT_COMMENT;
DROP TABLE EVENT;
DROP TABLE DIARY_MEMBER;
DROP TABLE DIARY;
DROP TABLE MEMBER;

/* 시퀀스 삭제 */
DROP SEQUENCE SEQ_USER_ITEM;
DROP SEQUENCE SEQ_SHOP_ITEM;
DROP SEQUENCE SEQ_TICKET_TRANSACTION;
DROP SEQUENCE SEQ_TICKET_BALANCE;
DROP SEQUENCE SEQ_INVITATION;
DROP SEQUENCE SEQ_EVENT_COMMENT;
DROP SEQUENCE SEQ_EVENT;
DROP SEQUENCE SEQ_DIARY_MEMBER;
DROP SEQUENCE SEQ_DIARY;
DROP SEQUENCE SEQ_MEMBER;
